import sys
import os
import pickle
import numpy as np
import pandas as pd

# Production EPW transposer generated by WTM_directional_uv_urban.py.
# The ANN bundle is loaded once and all hourly predictions are performed in this
# process. No standalone ANN subprocess is launched.

MODEL_FILENAME = "<STATIONNAME>_ann_model.pkl"


def load_ann_bundle(model_filename=MODEL_FILENAME):
    if not os.path.isfile(model_filename):
        raise FileNotFoundError(
            f"Model file '{model_filename}' was not found. Train the ANN first."
        )

    with open(model_filename, "rb") as model_file:
        bundle = pickle.load(model_file)

    models = bundle.get("models", {})
    if not models:
        raise ValueError("The model bundle contains no directional ANNs.")

    # Model indexes are rounded station directions. Convert equivalent float
    # keys to stable integer directions once when the model is loaded.
    models_by_direction = {}
    for original_key, model in models.items():
        direction_key = int(round(float(original_key))) % 360
        if direction_key in models_by_direction:
            raise ValueError(
                f"Duplicate ANN model for direction index {direction_key} degrees."
            )
        models_by_direction[direction_key] = model

    directions = sorted(models_by_direction)
    return models_by_direction, directions


def select_direction_pair(station_dir, directions):
    """Return lower index, upper index, and upper-model interpolation weight."""
    station_dir = float(station_dir) % 360.0

    if len(directions) == 1:
        return directions[0], directions[0], 0.0

    for direction in directions:
        if abs(station_dir - direction) < 1.0e-9:
            return direction, direction, 0.0

    extended_directions = directions + [directions[0] + 360]
    query_extended = station_dir
    if query_extended < directions[0]:
        query_extended += 360.0

    for lower_extended, upper_extended in zip(
        extended_directions[:-1], extended_directions[1:]
    ):
        if lower_extended < query_extended < upper_extended:
            lower_key = int(lower_extended) % 360
            upper_key = int(upper_extended) % 360
            weight = (
                (query_extended - lower_extended)
                / (upper_extended - lower_extended)
            )
            return lower_key, upper_key, weight

    # Numerical fallback at the circular boundary.
    lower_extended = float(directions[-1])
    upper_extended = float(directions[0] + 360)
    if query_extended <= directions[-1]:
        query_extended += 360.0
    weight = (
        (query_extended - lower_extended)
        / (upper_extended - lower_extended)
    )
    return directions[-1], directions[0], weight


def predict_wind_speed(
    models_by_direction,
    directions,
    station_wspd,
    station_dir,
    target_x,
    target_y,
    target_zground,
):
    """Predict local wind speed without producing runtime feedback."""
    lower_key, upper_key, weight = select_direction_pair(
        station_dir, directions
    )

    input_data = pd.DataFrame(
        [[station_wspd, target_x, target_y, target_zground]],
        columns=["station_wspd", "target_x", "target_y", "target_zground"],
    )

    uv_lower = models_by_direction[lower_key].predict(input_data)[0]
    if lower_key == upper_key:
        uv_interpolated = uv_lower
    else:
        uv_upper = models_by_direction[upper_key].predict(input_data)[0]
        uv_interpolated = (
            (1.0 - weight) * uv_lower
            + weight * uv_upper
        )

    return max(
        0.0,
        float(np.hypot(uv_interpolated[0], uv_interpolated[1])),
    )


def modify_epw_file(filename, project_site_x, project_site_y, project_site_zground):
    if not os.path.isfile(filename):
        raise FileNotFoundError(f"EPW file '{filename}' was not found.")

    models_by_direction, directions = load_ann_bundle()

    base, extension = os.path.splitext(filename)
    output_filename = f"{base}_ANN{extension}"
    transposed_records = 0

    with open(filename, "r", encoding="latin-1", newline="") as input_file, \
         open(output_filename, "w", encoding="latin-1", newline="") as output_file:
        for line in input_file:
            # Preserve EPW header lines exactly. Data records contain at least
            # 35 comma-separated fields, with direction at 20 and speed at 21.
            stripped_line = line.rstrip("\r\n")
            parts = stripped_line.split(",")

            if len(parts) >= 35 and parts[0].strip().isdigit():
                try:
                    station_dir = float(parts[20]) % 360.0
                    station_wspd = max(0.0, float(parts[21]))
                    predicted_speed = predict_wind_speed(
                        models_by_direction,
                        directions,
                        station_wspd,
                        station_dir,
                        project_site_x,
                        project_site_y,
                        project_site_zground,
                    )
                    parts[21] = f"{predicted_speed:.1f}"
                    stripped_line = ",".join(parts)
                    transposed_records += 1
                except (ValueError, IndexError):
                    # Preserve malformed or missing EPW records unchanged.
                    pass

            output_file.write(stripped_line + "\n")

    # One concise completion message only. No hourly or ANN-level feedback.
    print(
        f"Completed: {transposed_records} EPW records transposed. "
        f"Output: '{output_filename}'."
    )
    return output_filename


if __name__ == "__main__":
    if len(sys.argv) != 5:
        print(
            "Usage: python <SCRIPT> <epw_filename> "
            "<project_site_x> <project_site_y> <project_site_zground>"
        )
        sys.exit(1)

    try:
        epw_filename = sys.argv[1]
        project_site_x = float(sys.argv[2])
        project_site_y = float(sys.argv[3])
        project_site_zground = float(sys.argv[4])
        modify_epw_file(
            epw_filename,
            project_site_x,
            project_site_y,
            project_site_zground,
        )
    except (ValueError, FileNotFoundError) as error:
        print(f"Error: {error}")
        sys.exit(1)
